apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: tax-calculator-pipeline
spec:
  params:
    - name: IMAGE
      type: string
  workspaces:
    - name: source
  tasks:
    - name: test
      taskRef:
        name: tax-calculator-test
      workspaces:
        - name: source
          workspace: source
    - name: build
      runAfter: [test]
      taskRef:
        name: tax-calculator-build
      params:
        - name: IMAGE
          value: $(params.IMAGE)
      workspaces:
        - name: source
          workspace: source
    - name: deploy
      runAfter: [build]
      taskRef:
        name: tax-calculator-deploy
      params:
        - name: IMAGE
          value: $(params.IMAGE)
