apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: npm
spec:
  workspaces:
    - name: source
  params:
    - name: args
      type: array
      default: ["install"]
  steps:
    - name: npm-exec
      image: node:20-buster-slim
      workingDir: $(workspaces.source.path)
      script: |
        npm $(params.args)
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: jasmine
spec:
  workspaces:
    - name: source
  steps:
    - name: test
      image: node:20-buster-slim
      workingDir: $(workspaces.source.path)
      script: |
        npm install
        npx jasmine